### ISSUE TITLE
Visual indication of status unavailable when collector not running.

### ISSUE THREAD

**Issue by nistorj** [ssinyagin/torrus-newfeatures#22]
<img width="572" alt="screen shot 2017-01-15 at 10 27 50 am" src="https://cloud.githubusercontent.com/assets/13228234/21964053/c1e0f280-db12-11e6-9463-9591109bc8f3.png">

From the screenshot you can see that there is a blank icon for entries in which the collector is not collecting for, minor visual issue.

**Comment by ssinyagin** [comment]
thanks, fixed in 88507de
