### ISSUE TITLE
IPv6 support for redis in v3

### ISSUE THREAD

**Issue by 42wim** [ssinyagin/torrus-newfeatures#24]
I'm trying out the v3 tree, but our redis-cluster is ipv6-only which perl-Redis doesn't support.

Redis::Fast (https://metacpan.org/release/Redis-Fast) does support it though and is a drop-in replacement for perl-Redis.

Another issue is redis-distlock which needs Redis (but replacing it with Redis::Fast just works fine).

**Comment by ssinyagin** [comment]
I think I can get rid of Distlock completely. Its use case is very limited and can be worked around. Just let me finish with a tricky issue in dependency tracking :)
See also my private email

**Comment by ssinyagin** [comment]
please see 937333e and test

**Comment by 42wim** [comment]
works great, thanks
