### ISSUE TITLE
Incorrect "Datasource exists in RRD file, but it is not updated"

### ISSUE THREAD

**Issue by 42wim** [ssinyagin/torrus-newfeatures#28]
I'm getting messages about datasource exists in RRD file but it is not updated. (in different trees)

```
[23-Feb-2017 14:51:01*] Datasource exists in RRD file, but it is not updated: ifHCOutUcastPkts in /var/lib/torrus/collector_rrd/D5/1.2.3.4_d8_if-mib.rrd
```

But when I take a snapshot of it
```torrus snapshot --tree=mytree``` 

I can see clearly that the ds is exists ```<param name="rrd-ds" value="ifHCOutUcastPkts"/>```

Also tested on a clean instance (cleared gitrepo/redis)

```
                <leaf name="Packets_Out">
                  <param name="collector-dispersed-timeoffset" value="yes"/>
                  <param name="collector-instance" value="0"/>
                  <param name="collector-period" value="300"/>
                  <param name="collector-timeoffset" value="60"/>
                  <param name="collector-timeoffset-hashstring" value="%system-id%:%interface-nick%"/>
                  <param name="collector-timeoffset-max" value="300"/>
                  <param name="collector-timeoffset-min" value="0"/>
                  <param name="collector-timeoffset-step" value="60"/>
                  <param name="comment" value="Output packet counter for the interface"/>
                  <param name="ds-type" value="collector"/>
                  <param name="graph-legend" value="Packets out"/>
                  <param name="graph-lower-limit" value="0"/>
                  <param name="interface-nick" value="d8"/>
                  <param name="nodeid" value="%nodeid-interface%//outpackets"/>
                  <param name="nodeid-device" value="%system-id%"/>
                  <param name="nodeid-interface" value="if//%nodeid-device%//HP VC FlexFabric 10Gb/24-Port Module 4.50 d8"/>
                  <param name="precedence" value="880"/>
                  <param name="rrd-create-dstype" value="COUNTER"/>
                  <param name="rrd-create-max" value="1e15"/>
                  <param name="rrd-ds" value="ifHCOutUcastPkts"/>
                  <param name="snmp-host" value="1.2.3.4"/>
                  <param name="snmp-object" value="$ifHCOutUcastPkts.%ifindex-map%"/>
                  <param name="snmp-object-type" value="COUNTER64"/>
                  <param name="storage-type" value="rrd"/>
                  <param name="system-id" value="%snmp-host%"/>
                  <param name="vertical-label" value="pps"/>
                  <!--token: 04a801c1eb30c8eceef1e1f7ea52e6f183b85e59-->
```

**Comment by ssinyagin** [comment]
in my early production instance, I see only one interface generating such errors. Is it also the case with you, that only specific ports are failing to monitor? How many per tree? 

Is it only IF-MIB interfaces, or other MIBs too?

**Comment by 42wim** [comment]
I've noticed that it didn't happen on my previous builds.
I've reverted back to a previous point in time (to commit https://github.com/ssinyagin/torrus-newfeatures/commit/bbab4a12dc8f4b65c72f38cc7aa0a3f22627e8d0) and now it doesn't happen.

Looking at the commits I guess https://github.com/ssinyagin/torrus-newfeatures/commit/85b7b6b0956ee9daa5348fd681ed948e4b29eaf1 could be the one that caused it, I'm going to do some more tests.

**Comment by 42wim** [comment]
Update: 
* commit bbab4a1 is ok
* commit 85b7b6b is also still ok
* commit 3ff3843 is bad
* now trying commit c8cc445

Not all trees have it, 2 out of 9 trees. 
Tree1 has 1608 errors, tree2 has 1017 errors. 
Only happens on IF-MIB interfaces.

**Comment by 42wim** [comment]
Ok, seems that c8cc445 is the culprit, 320c54c is still ok

**Comment by ssinyagin** [comment]
Thanks a lot, I'll check it during the weekend.

**Comment by ssinyagin** [comment]
Wim, I found the misbehavior, but haven't yet found the reason for it. Looks like the object cache does not get updated properly:

by default, "collector-dispersed-timeoffset"  is set to "yes", and Writer.pm calculates new offset values for collector nodes. But as a result, the agent branch "TREE_collector_00XX" does not always get correct timeoffsets. For some arbitrary leaves, it's still "collector-timeoffset":"10".

So, the collector needs to send all SNMP requests for an If-MIB interface at once, so that it can update the RRD file. But some of the fields are requested at a different schedule, and that produces this error.

I need to figure out why the old collector-timeoffset value is stuck in the cache.

**Comment by ssinyagin** [comment]
found it. b2f9bc9 should fix the problem. After upgrading, you can run compiler with -f option, and that will fix the agent configs.

**Comment by 42wim** [comment]
Can confirm, it's fixed. Thanks for the quick patch!

**Comment by ssinyagin** [comment]
I made a bit of improvement in new commits now.

**Comment by 42wim** [comment]
just tested, still ok :-)

**Comment by 42wim** [comment]
Seems like it happened again (for 1 switch). I did an update (not from scratch) on the big tree.
```
[27-Feb-2017 16:18:33 ] Preparing a commit...
[27-Feb-2017 16:18:43 ] Finished post-processing of 2829 nodes
[27-Feb-2017 16:23:33 ] Data validation...
[27-Feb-2017 16:23:38 ] Finished validation on 2543 leaves
[27-Feb-2017 16:23:38 ] Configuration has compiled successfully
[27-Feb-2017 16:23:38 ] Updating agent configurations
[27-Feb-2017 16:23:47 ] Updated: 595, Deleted: 34 leaf nodes
[27-Feb-2017 16:24:34 ] Running Git garbage collector...
```

Now I'm getting for every port on that one switch errors about ifOutDiscards
```
Datasource exists in RRD file, but it is not updated: ifOutDiscards in /srv/torrus/collector_rrd/AD/1.2.3.4_Fa0_10_if-mib.rrd
```

I've ran ```torrus snapshot``` which took 13Gb ram on its peak btw, and when I looked up the entries this time they also didn't exist in the snapshot file.

Does this mean that some snmp info was lost while discovering the device ?

**Comment by ssinyagin** [comment]
you need to use -f flag in compiler once after the upgrade. Then it will update the agent configs properly.

**Comment by 42wim** [comment]
Didn't use the "-f flag" because the tree was started from scratch 6 hours ago after your b2f9bc9 commit.
I did yet again an update (before I read your comment here, also without -f flag) and now the error is gone.

So could that be an snmp issue ?

**Comment by ssinyagin** [comment]
the -f flag is equivalent to having empty database and re-building it from scratch. So, you might have the old data in gitrepo from previous tests?

**Comment by 42wim** [comment]
no, I empty the gitrepo every time I rebuild torrus source.
