### ISSUE TITLE
With the commit: deleted obsoleted doc/rrfw_torrus_migration.pod.in still issues

### ISSUE THREAD

**Issue by nistorj** [ssinyagin/torrus-newfeatures#31]
Hi Stan,

With "deleted obsoleted doc/rrfw_torrus_migration.pod.in" it still shows in the v3 pull:

/usr/bin/pod2text nodeid_usage.pod > nodeid_usage.txt
/root/torrus-newfeatures-3/src/setup_tools/substvars.sh reporting_setup.pod.in  > reporting_setup.pod
/usr/bin/pod2text reporting_setup.pod > reporting_setup.txt
/root/torrus-newfeatures-3/src/setup_tools/substvars.sh rpnexpr.pod.in  > rpnexpr.pod
/usr/bin/pod2text rpnexpr.pod > rpnexpr.txt
make[2]: *** No rule to make target 'rrfw_torrus_migration.pod.in', needed by 'rrfw_torrus_migration.pod'.  Stop.
make[2]: Leaving directory '/root/torrus-newfeatures-3/src/doc'
Makefile:487: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/torrus-newfeatures-3/src/doc'
Makefile:577: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
root@lgstasrmgmt01:~/torrus-newfeatures-3/src# grep -r rrfw_torrus_migration.pod.in
doc/Makefile:		rrfw_torrus_migration.pod.in \
doc/Makefile.in:		rrfw_torrus_migration.pod.in \
doc/Makefile.am:		rrfw_torrus_migration.pod.in \
root@lgstasrmgmt01:~/torrus-newfeatures-3/src#

had to remove all references everywhere for it.

**Comment by ssinyagin** [comment]
duh. of course. I'll clean that up.

**Comment by ssinyagin** [comment]
finxed in f29318f
